'use strict';
var Interpreter_js_1 = require('./src/interpreter/Interpreter.js');
exports.Interpreter = Interpreter_js_1.default;
var Parser_js_1 = require('./src/parser/Parser.js');
exports.Parser = Parser_js_1.default;
var TypeChecker_js_1 = require('./src/typechecker/TypeChecker.js');
exports.StaticChecker = TypeChecker_js_1.default;
var Interpretable_js_1 = require('./src/transformer/Interpretable.js');
exports.InterpretableTransform = Interpretable_js_1.default;
var Checkable_js_1 = require('./src/transformer/Checkable.js');
exports.DeclarationTransform = Checkable_js_1.default;
var TreeToRPN_js_1 = require('./src/transformer/TreeToRPN.js');
exports.TreeToRPNTransform = TreeToRPN_js_1.default;
